# SPDX-FileCopyrightText: 2026 Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
#
# SPDX-License-Identifier: CC0-1.0

[project]
variant = "classic"
site_name = "Microbial Data Standard"
site_description = "Modern microbial data standardization"
site_author = "Bioindustry 4.0 WP6"
site_dir = "public/docs"
docs_dir = "packages/microbial_strain_data_docs/src"
use_directory_urls = true
extra_css = [
    "extra_css/extra.css",
]
extra_javascript = [
    "extra_js/mermaid.min.js",
]
copyright = "Copyright &copy; 2026 Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH, Maintained by the WP6 Team of the <a href='https://www.bioindustry4.eu/'>Bioindustry 4.0 project</a>"
language = "en"
repo_name = "LeibnizDSMZ/microbial-data-standard"
repo_url = "https://github.com/LeibnizDSMZ/microbial-data-standard"
repo_license = "MIT"

[project.theme]
features = [
    "header.autohide",
    "navigation.tabs",
    "navigation.top",
    "toc.integrate",
    "navigation.prune",
    "navigation.instant",
]
font = false
logo = "images/transparent_white_thick.png"

[project.theme.icon]
repo = "fontawesome/brands/git-alt"

[project.theme.palette]
primary = "custom"
accent = "custom"

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.abbr]

[project.markdown_extensions.toc]
toc_depth = 1
permalink = "#"
baselevel = 1
separator = "_"

[project.plugins.search]

[project.plugins.autorefs]

[project.plugins.literate_nav]
nav_file = "README.md"
implicit_index = true

[project.plugins.mkdocstrings.handlers.python]
inventories = [
    "https://docs.python.org/3/objects.inv",
]
paths = [
    "packages/microbial_strain_data_model/src",
    "packages/microbial_strain_data_utils/src",
]

[project.plugins.mkdocstrings.handlers.python.options]
heading_level = 2
allow_inspection = true
find_stubs_package = true
show_submodules = true
show_root_heading = false
unwrap_annotated = true
show_source = true
show_signature = true
show_signature_annotations = true
show_signature_type_parameters = true
show_attribute_values = true
show_symbol_type_heading = true
show_docstring_attributes = false
show_docstring_functions = false
show_docstring_classes = false
show_docstring_type_aliases = false
show_docstring_modules = false
show_docstring_description = true
show_docstring_examples = true
show_docstring_other_parameters = false
show_docstring_parameters = true
show_docstring_raises = true
show_docstring_receives = true
show_docstring_returns = true
show_docstring_type_parameters = true
show_docstring_warns = true
show_docstring_yields = true
show_overloads = true
show_bases = true
show_labels = true
show_if_no_docstring = false
skip_local_inventory = false
merge_init_into_class = true
separate_signature = false
signature_crossrefs = true
modernize_annotations = true
overloads_only = true
annotations_path = "brief"
parameter_headings = true
type_parameter_headings = true
group_by_category = true
summary = false
docstring_style = "google"
docstring_section_style = "table"
filters = [
    "!^_",
    "!^__",
]
extensions = [
    { griffe_pydantic = { schema = false } },
]

[project.plugins.mkdocstrings.handlers.python.options.docstring_options]
ignore_init_summary = false
trim_doctest_flags = true

[[project.nav]]
About = [
    "index.md",
    "background.md",
    "technical.md",
    "license.md",
]

[[project.nav]]
"Data schema" = [
    "schema/01. bioSafety.md",
    "schema/02. collections.md",
    "schema/03. cultivationMedia.md",
    "schema/04. enzymes.md",
    "schema/05. fattyAcidProfiles.md",
    "schema/06. gcContent.md",
    "schema/07. growthConditions.md",
    "schema/08. halophily.md",
    "schema/09. hemolysis.md",
    "schema/10. identifier.md",
    "schema/11. knownApplications.md",
    "schema/12. legal.md",
    "schema/13. literature.md",
    "schema/14. metabolites.md",
    "schema/15. morphType.md",
    "schema/16. morphology.md",
    "schema/17. organismType.md",
    "schema/18. origin.md",
    "schema/19. otherMedia.md",
    "schema/20. pathogenicity.md",
    "schema/21. primaryId.md",
    "schema/22. relatedData.md",
    "schema/23. sequences.md",
    "schema/24. sources.md",
    "schema/25. sporeFormation.md",
    "schema/26. staining.md",
    "schema/27. taxon.md",
    "schema/28. tolerances.md",
    "schema/29. typeStrain.md",
    "schema/30. version.md",
    "schema/31. wallConstituents.md",
]

[[project.nav]]
Python = [
    "python/microbe.md",
    "python/sub_classes.md",
]

[[project.nav]]
Graph = [
    "graph.md",
]

[[project.nav]]
Examples = [
    "examples/bacteria.md",
    "examples/fungi.md",
]
