site_name: Microbial data standard
site_description: A new microbial data standard.
site_author: WP6 of Bioindustry 4.0 (funded by the EU)

theme:
  name: material
  logo: stylesheets/transparent_white_thick.png
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: bi_light
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

extra_css:
- stylesheets/extra.css

plugins:
- search
- autorefs
- literate-nav:
    nav_file: README.md
    implicit_index: true
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [../../src]
        options:
          extensions:
          - griffe_fieldz: {include_inherited: true}
          show_submodules: true
          show_root_heading: false
          heading_level: 2

markdown_extensions:
- abbr
- attr_list
- md_in_html
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- toc:
    toc_depth: 2
    permalink: '#'
    baselevel: 1
    separator: _

docs_dir: ../../docs

nav:
- About:
  - index.md
  - Microbial Data: background.md
  - Technical Concept: technical.md
  - Call to Action: call.md
  - License: license.md
- Data Schema: schema/
- Python:
  - Microbe Class: python/microbe.md
  - Sub Classes: python/sub_classes.md
- Graph: graph.md
- Examples: examples/



copyright: Copyright &copy; 2024 Julius Witte, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH, Maintained by the WP6 Team of the  <a href="https://bioindustry4.hub.inrae.fr/">Bioindustry 4.0 project</a>

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/LeibnizDSMZ/microbial-data-standard
    name: LeibnizDSMZ/microbial-data-standard

repo_url: https://github.com/LeibnizDSMZ/microbial-data-standard
repo_name: LeibnizDSMZ/microbial-data-standard
